### ISSUE TITLE
tolerant handling for metadata

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/flaschenpost#12]
> If you want to provide additional meta data, use an object as second parameter.

I can see that's written in your documentation. still I would ask to change this to a more tolerant handling, also allowing to pass a string or number as second parameter.
sometimes I just want to pass on whatever I got from some other call, without having to wrap it into an additional object just to satisfy flaschenpost.

**Comment by goloroden** [comment]
We could do this, and as far as I can see the only place where it really affects anything, is [here](https://github.com/thenativeweb/flaschenpost/blob/eebad63f33b12b1983f9eb5704452308450caacc/lib/formatters/HumanReadable.js#L50-L56).

Could you please send a PR with the changes you would like to see, updated tests, and documentation?

**Comment by goloroden** [comment]
@stefanheine I have seen your PR and now I'm going to work on it. Hence, I'm closing this issue, and will get back to you personally, if there are any questions left.
