### ISSUE TITLE
prevent throwing exception in flaschenpost

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/flaschenpost#13]
my code has:

> const uncaughtExceptionHandler = function(err) {
>   logger.error('Uncaught exception:\n', err);
> 
>   process.exit('66');
> };

but somewhere else I called

> logger.info('Language', language.specifiedAlias);

This caused my app to exit(66) without any further error message, since the flaschenpost itself caused the exception.
I would like to see a low-level component like flaschenpost not to throw exceptions, at least wherever with some reasonable effort you could implement a tolerant handling instead.

**Comment by goloroden** [comment]
Thanks for reporting this issue!

I have two questions on it:

First, why did flaschenpost fail? You say that calling

> logger.info('Language', language.specifiedAlias);

caused your app to fail, because flaschenpost threw an exception. What happened here?

Second, what's your proposal how to deal with situations where flaschenpost encounters an internal error? If we should not throw an exception, what should we do instead? We can not simply just print a log message, as logging itself my be in a corrupt state. So, what is the alternative?

**Comment by stefanheine** [comment]
> Second, what's your proposal how to deal with situations where flaschenpost encounters an internal error? If we should not throw an exception, what should we do instead? We can not simply just print a log message, as logging itself my be in a corrupt state. So, what is the alternative?

looking at your tests, I see a number that I would change:

>       test('throws an error when no message is given.', done => {
>         const logger = flaschenpost.getLogger(__filename);
> 
>         assert.that(() => {
>           logger.info();
>         }).is.throwing('Message is missing.');

I would allow this, and print an empty message in the log output instead. the rest of the log message (code location, meta data) might be interesting.

>       test('throws an error when message is not a string.', done => {
>         const logger = flaschenpost.getLogger(__filename);
> 
>         assert.that(() => {
>           logger.info(42);
>         }).is.throwing('Message must be a string.');
>         done();
>       });

just stringify the data and log the output.

the case I experienced is not covered in your tests yet:

> logger.info('valid string', 'string as meta data');

and again, I would change this to print whatever is possible to print, instead of throwing an exception.



> where flaschenpost encounters an internal error?

throwing an exception if the flaschenpost logger is getting initialized with invalid data is ok.
but once initialized, issues like in the examples above should not be counted as internal error, but be handled.

let me know if you agree, and I'll change a PR with the changes as proposed above.

**Comment by goloroden** [comment]
We need to make sure that we do not mix up things here.

One thing is allow handling of non-object types for metadata. This is tracked in #12.

Regarding exceptions, it's not yet clear to me how to do this in a reliable way. Maybe I missed your point, but IMHO we do not yet have an answer for:

> Second, what's your proposal how to deal with situations where flaschenpost encounters an internal error? If we should not throw an exception, what should we do instead? We can not simply just print a log message, as logging itself my be in a corrupt state. So, what is the alternative?

**Comment by stefanheine** [comment]
I would review the code and look at all exceptions generated inside flaschenpost, or those - in case there are such - caught from called modules and passed back.
those, that could be handled, especially at runtime, should be changed to not throw an exception. maybe this is just the issue about the metadata types, but maybe there is more.

**Comment by goloroden** [comment]
The question is how to handle them?

**Comment by stefanheine** [comment]
that depends on the exception. look at the examples I listed above. these are easy to handle. I would need to look at the code to see if there are more.
but handling the examples I listed above would be a good start.

**Comment by stefanheine** [comment]
pull request created. let me know what you think.

**Comment by goloroden** [comment]
Thanks for this!

I will have a look at this soon, and get back to you.

**Comment by goloroden** [comment]
@stefanheine I have seen your PR and now I'm going to work on it. Hence, I'm closing this issue, and will get back to you personally, if there are any questions left.
