### ISSUE TITLE
flaschenpost-normalize & flaschenpost-uncork: command not found

### ISSUE THREAD

**Issue by quarterpi** [thenativeweb/flaschenpost#144]
As per the documentation [https://docs.wolkenkit.io/latest/reference/debugging-an-application/viewing-log-messages/](url) `wolkenkit logs | flaschenpost-normalize | flaschenpost-uncork
` returns command not found for flaschenpost-normalize and flaschenpost-uncork after installing flaschenpost with `npm install -g flaschenpost`.

@version 4.0.1

I also get an error when trying to `follow` the logs stating that I am using a self-signed certificate. Doesn't seem like it would be related to a `command not found` error, but I thought I'd mention it anyway.

**Comment by goloroden** [comment]
Hi @quarterpi 👋 

Yes, what you describe is true – the mentioned commands have been removed with version `3.0.0`. So, to make things work you need to install a version < `3.0.0`, e.g. `2.1.0`, by running

```shell
$ npm install -g flaschenpost@2.1.0
```

Afterwards, the commands `flaschenpost-normalize` and `flaschenpost-uncork` will work as expected. I know that this is missing in the wolkenkit documentation, but we will change so many things in the upcoming version of wolkenkit that we do not put too much effort any more into the existing documentation.

I hope this helps 😊

**Comment by quarterpi** [comment]
@goloroden Ahh, that explains it. 
Very helpful as usual. 
Thanks!
