### ISSUE TITLE
Extend log messages send to elastic with custom env vars

### ISSUE THREAD

**Issue by holger-rode** [thenativeweb/flaschenpost#17]
We are looking to add additional meta information to elastic search in every log message like docker_host and environment.

Please extend flaschenpost-to-elastic.js so that environment vars with prefix "FLASCHENPOST_TO_ELASTIC_" will be written into elasticsearch fields. 

Example: 
FLASCHENPOST_TO_ELASTIC_DOCKER_HOST="mydockerhost"
FLASCHENPOST_TO_ELASTIC_ENVIRONMENT="production"
would add docker_host and environment to the message
message['docker_host'] = 'mydockerhost'
message['environment'] = 'production'

I'd propose to keep environment vars completely upper case, but lower case the variable names when send to elastic.

**Comment by goloroden** [comment]
Hi @holger-rode 😊 

First of all, thanks for your ideas!

I have been thinking about them for a few days now, and I'm not sure whether we will introduce support for this. It's not that your ideas are bad – it's just that we don't _use_ the EasticSearch connection ourselves.

This makes it hard to catch up with development there.

Just as an idea: Supposed we split this repository into two (one for flaschenpost itself, and one for the ES connector), could you imagine to take over the ES repo?

**Comment by holger-rode** [comment]
Hi Golo,

thx for the fast response ...grr... would have replied long since if I had noticed that Github mails were going into my spam folder.

Sounds like a good idea and yes, would be happy to take that repo on if you split it out.

**Comment by goloroden** [comment]
Okay. I will do this within the next few days, and inform you once it has been done.
