### ISSUE TITLE
Allow flaschenpost to be configured with a stream other than stdout

### ISSUE THREAD

**Issue by strangedev** [thenativeweb/flaschenpost#819]
Currently, flaschenpost logs to stdout exclusively.
While this is the correct thing to do in most, if not all, applications, this becomes a problem in testing.
When running parts of an application using a test runner, the log messages pollute the output, making it hard to see what is going on.

The issue here is, that we rely on the fact that an application using flaschenpost can always be executed in its own process, allowing us to use standard operating system mechanisms to redirect the log stream. This is not the case during testing, where it is not always possible or practical to isolate the code under test in a way that allows us to redirect stdout.

I propose that we make the stream flaschenpost writes to configurable. We could, and imho should, leave stdout as a default, as that is what is correct in most cases and we should not encourage handling log redirection and delivery inside of the application.

This would allow us to buffer the log stream during testing, and only display ist when running into errors.

**Comment by goloroden** [comment]
Just a quick thought on this one:

Instead of handing in a stream, we could also hand in a function that does *something*. This can be writing to stdout, writing to another stream, but even (if someone needs it) writing to a file, or to the network, a database, or anything else …

For us, this wouldn't make much of a difference, but we could gain way more flexibility with this approach.

@strangedev What do you think on this?

**Comment by strangedev** [comment]
> For us, this wouldn't make much of a difference, but we could gain way more flexibility with this approach.

I think flexibility wise the two solutions are more or less identical. You can attach a consumer to the stream to achieve anything a function could.

The question is, imho, which case we want to support first, writing to a stream, or writing to something else like a buffer. Since we don't want to encourage redirecting logs in an actual application, the function approach seems more suitable to me at the moment.

We could implement the default behavior in the same way, by supplying a function that writes to stdout by default.

**Comment by strangedev** [comment]
Another benefit of the function approach would be that the mentioned use case (buffering logs during testing) is much easier to implement than using streams.

**Comment by strangedev** [comment]
Sure, but I'm not too familiar with the inner workings of flaschenpost at the moment, so I will need some time to come up with something workable.

**Comment by goloroden** [comment]
No problem 😊

**Comment by yeldiRium** [comment]
I had a quick look at things and I see two ways to go here.

We currently already have the option to supply a custom `Formatter`, which are functions of type `(logEntry: LogEntry) => string`. The `log` function on a `Logger` creates a `LogEntry`, let's the `Formatter` format it and then writes the resulting `string` to `stdout`.

One the one hand this means that there already is a way to format log entries in a customizable way, so we could argue that a custom logging function should only receive the resulting `string` and do with that whatever it wants. Such a log function would basically read `(logMessage: string) => void` or potentially `(logMessage: string) => Promise<void>`.

One the other hand I think the custom log function should know the log level of a `LogEntry` and have access to the `Configuration` of the `Flaschenpost` instance. Any decisions about wether to log something should have already been made at that point, but I don't see why the log function should not be allowed to do so again. So I would personally prefer a log function that looks like `(args: { logEntry: LogEntry; configuration: Configuration }) => Promise<void>`. The default implementation for this would call the formatter on the log entry and write the result to stdout. A custom implementation may choose to ignore the formatter or to use it - and write the result to wherever or even drop it.

What do you all think about these options? @goloroden @strangedev @dotKuro

**Comment by strangedev** [comment]
I think the second option is too powerful and would lead to confused code. The formatter is responsible for applying formatting, we should not let the log function decide whether to apply it. The log function should have a very narrow purpose IMHO - receiving formatted log entries and writing them to some output. So I prefer the first option.
