### ISSUE TITLE
Typescript rejects error objects as metadata

### ISSUE THREAD

**Issue by ali-baykal** [thenativeweb/flaschenpost#899]
Hi guys,

when logging with .fata() or .error() I would like to pass the causing Error as metadata. However Typescript complains that `Argument of type 'Error' is not assignable to parameter of type 'Record<string, unknown>'.
  Index signature for type 'string' is missing in type 'Error'.` In my opinion it should be allowed to pass an error. Even further it would be great if there were versions of .fatal() and .error() that took an Error as their main argument.

Is the current state a deliberate design decision? And if yes, what is your reasoning?

Cheers,
Ali

**Comment by goloroden** [comment]
Hey @ali-baykal 👋 

Thanks for bringing up the issue.

The way we typically handle this is as follows. Instead of

```typescript
logger.fatal('Something went wrong.', err);
```

simply use:

```typescript
logger.fatal('Something went wrong.', { err });
```

This way, it works, and you get the information on the terminal that the property describes an error.
